### PR TITLE
Fix IPv6 TCP tunnel display formatting

### LINKED ISSUE #1979: [bug] easytier-cli peer cmmand, the tunnel column sometimes becomes misaligned when displaying IPv6 TCP tunnels.
### 问题简要描述 / Brief Description

When running `easytier-cli peer`, the tunnel column sometimes becomes misaligned when displaying IPv6 TCP tunnels.

Example output:

| ipv4            | hostname     | cost  | lat(ms) | loss | rx        | tx        | tunnel                                     | NAT            | version        |
|-----------------|--------------|-------|---------|------|-----------|-----------|---------------------------------------------|----------------|----------------|
| 10.126.126.3/24 | PC           | Local | -       | -    | -         | -         | -                                           | NoPAT          | 2.5.0-88a45d11 |
|                 | PublicServer | p2p   | 13.10   | 0.0% | 3.33 kB   | 3.61 kB   | txt-tcp://[xxxx:xxxx:xxxx:xxxx]:110106      | Restricted     | 2.4.5-4c4d172e |
| 10.126.126.1/24 | ImmortalWrt  | p2p   | 9.58    | 0.0% | 965.89 kB | 214.00 kB | tcp,udp6                                    | PortRestricted | 2.5.0-88a45d11 |

Problem:
The tunnel field shows:

txt-tcp://[xxxx:xxxx:xxxx:xxxx]:110106

This appears to be misformatted.  
The correct format should likely be:

tcp6://[xxxx:xxxx:xxxx:xxxx]:11010

It looks like:
1. The protocol prefix is incorrect (`txt-tcp`).
2. The port is incorrectly concatenated (`110106` instead of `11010`).

### 环境信息 / Environment Information

easytier-cli 2.5.0-88a45d11

### 节点配置 / Node Configurations

**Public Server Config**
```
############### TOML ###############

hostname = "EXAMPLE_PUBLIC-SERVER"
dhcp = true
listeners = ["tcp://0.0.0.0:11010"]
rpc_portal = "0.0.0.0:0"
tcp_whitelist = []
udp_whitelist = []

[network_identity]
network_name = "default"
network_secret = ""

[flags]
relay_network_whitelist = "example-name"
```

### 日志信息 / Log Information

2026-03-10 17:35:34: [5afafe2a-03c6-470a-990f-7da9dba79dd1] new peer connection added. conn_info: my_peer_id: 2450094495, dst_peer_id: 2468862670, tunnel_info: Some(TunnelInfo { tunnel_type: "txt-tcp://[xxxx:xxxx:xxxx:xxxx]:11010", local_addr: Some(Url { url: "tcp://[xxxx:xxxx:xxxx:xxxx]:11335" }), remote_addr: Some(Url { url: "txt://et.example.com" }) })

### 重现步骤 / Reproduction Steps

1. Start publicserver using the configuration described above.
2. The txt is resolved to publicserver, with the domain name txt://et.example.com and the resolved content being: "tcp://[xxxx:xxxx:xxxx:xxxx]:11010"
3. The client connects to the public server using txt://et.example.com.

### 预期结果 / Expected Behavior

The correct peer command output should be:
| ipv4            | hostname     | cost  | lat(ms) | loss | rx        | tx        | tunnel                                     | NAT            | version        |
|-----------------|--------------|-------|---------|------|-----------|-----------|---------------------------------------------|----------------|----------------|
| 10.126.126.3/24 | PC           | Local | -       | -    | -         | -         | -                                           | NoPAT          | 2.5.0-88a45d11 |
|                 | PublicServer | p2p   | 13.10   | 0.0% | 3.33 kB   | 3.61 kB   | txt-tcp6://[xxxx:xxxx:xxxx:xxxx]:11010      | Restricted     | 2.4.5-4c4d172e |
| 10.126.126.1/24 | ImmortalWrt  | p2p   | 9.58    | 0.0% | 965.89 kB | 214.00 kB | tcp,udp6                                    | PortRestricted | 2.5.0-88a45d11 |

### 额外信息 / Additional Context

_No response_

### PR DESCRIPTION
**Pull request by fanyang89**
- Fix IPv6 tunnel display formatting in `easytier-cli peer` by normalizing compositee tunnel strings instead of appending `6` to the raw `tunnel_type`.
- Preserve connector prefixes such as `txt-` while rendering IPv6 tunnel schemes, and recover malformed values like `txt-tcp://[...]:110106` into `txt-tcp6://[...]:11010`.
- Reuse the same normalized formatting for CLI debug output and add regression tests covering plain IPv6, composite schemes, malformed ports, already-normalized values, and remote-address fallback.

Close #1979

### CODE REVIEW

File: easytier/src/proto/common.rs [hunk 1]
```diff
@@ -284,6 +284,99 @@ impl fmt::Display for Url {
     }
 }
 
+const IPV6_TUNNEL_SCHEMES: &[&str] = &["faketcp", "quic", "wss", "tcp", "udp", "ws", "wg"];
```
Comment (KKRainbow) [inline easytier/src/proto/common.rs]: #2026 中对这些 scheme 做了抽象，放到了 IpScheme 中，是否可以复用

Comment (fanyang89) [reply easytier/src/proto/common.rs]: IpScheme 目前受 feature gate 影响，直接复用后，不同 feature 组合的客户端在降级或混部场景下，可能会对同一条连接显示出不同的结果

Comment (fanyang89) [reply easytier/src/proto/common.rs]: 05694b7b925c9749c1e102892c2a4caf26f1076a

File: easytier/src/tunnel/mod.rs [hunk 2]
```diff
@@ -302,6 +302,28 @@ pub enum IpScheme {
 }
 
 impl IpScheme {
+    /// Returns the canonical scheme string as a `&'static str`.
+    ///
+    /// This duplicates `Display` (from strum) intentionally: callers like
+    /// `split_tunnel_scheme` need a `&'static str`, which `to_string()`
+    /// cannot provide.
```
Comment (ZnqbuZ) [inline easytier/src/tunnel/mod.rs]: 可以用 `strum::IntoStaticStr` 吧？

Comment (fanyang89) [reply easytier/src/tunnel/mod.rs]: 我没用过 strum，感谢指出。

Resolve at bd63672bbf67964bd4b3b7fd86c7b589bf54d9c6

File: easytier/src/proto/common.rs [hunk 3]
```diff
@@ -284,6 +285,100 @@ impl fmt::Display for Url {
...
+}
+
+fn normalize_tunnel_url(raw: &str, fallback_ipv6: Option<bool>) -> Option<String> {
+    let (raw_scheme, rest) = raw.split_once("://")?;
+
+    if let Some(rest) = rest.strip_prefix('[') {
+        let (host, remainder) = rest.split_once(']')?;
+        let raw_port = remainder.strip_prefix(':')?;
+        let port = normalize_tunnel_port(raw_port, true)?;
+        let scheme = normalize_tunnel_scheme(raw_scheme, true)?;
```
[the remark this answers is not in the document]
Comment (fanyang89) [reply easytier/src/proto/common.rs]: ade61d8bf97f9f48f34848da23439f546ac4aa25

File: easytier/src/proto/common.rs [hunk 4]
```diff
@@ -284,6 +285,100 @@ impl fmt::Display for Url {
...
+            format!("[{host}]")
+        } else {
+            host.to_string()
+        };
+
+        return Some(match url.port_or_known_default() {
+            Some(port) => format!("{scheme}://{host}:{port}"),
+            None => format!("{scheme}://{host}"),
+        });
+    }
```
[the remark this answers is not in the document]
Comment (fanyang89) [reply easytier/src/proto/common.rs:370]: ade61d8bf97f9f48f34848da23439f546ac4aa25

File: easytier/src/proto/common.rs [hunk 5]
```diff
@@ -284,6 +285,100 @@ impl fmt::Display for Url {
...
+                return Some((prefix, scheme, true));
+            }
+        }
+
+        if let Some(prefix) = raw_scheme.strip_suffix(scheme) {
+            if prefix.is_empty() || prefix.ends_with('-') {
+                return Some((prefix, scheme, false));
+            }
+        }
+    }
```
[the remark this answers is not in the document]
Comment (fanyang89) [reply easytier/src/proto/common.rs:304]: 092e6ed2fc38088a82422414011c1130570f707a
